### ISSUE TITLE
Sidebar Widget With No Title Top Border

### ISSUE THREAD

**Issue by turtlepod** [turtlepod/nevertheless#10]
1st Sidebar widget with no title need top border:
![nevertheless-widget-no-title](https://cloud.githubusercontent.com/assets/1705549/19540422/95f1eb0c-9689-11e6-81f1-b36e42142f98.png)

**Comment by andrewheald** [comment]
I just added custom CSS to get around this, so it wasn't a problem:
`div#sidebar-primary { border-top: 1px solid #ccc; }`

**Comment by turtlepod** [comment]
Thank you @andrewheald

**Comment by andrewheald** [comment]
In this case, the site only has just one box on the sidebar, and that is untitled. I'm not sure if my hack would work if there were more than one untitled box. I suspect not because I'm affecting the container div rather than the box div.

**Comment by andrewheald** [comment]
Actually, I've just changed it to `section.widget { border-top: 1px solid #ccc; }` which seems to be more all-purpose.

**Comment by andrewheald** [comment]
No, my first attempt was better because you don't want a top border on lower boxes because there's already a bottom border on the box above.

**Comment by turtlepod** [comment]
@andrewheald thank you so much for the input. I just updated the theme with the fix, (v.1.5.1)
Let me know if you see issues with this fix.

I'll close this issue, but feel free to open a new topic/issue.
I really appreciate your input.

**Comment by andrewheald** [comment]
@turtlepod - It works on my client's site - custom CSS workaround removed. Thank you to you too.
